language: r

sudo: required

r_packages:
  - covr
  - devtools

r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

addons:
  apt:
    packages:
      - libharfbuzz-dev
      - libfribidi-dev
after_success:
  - Rscript -e 'library(covr); codecov()'
